// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD46HmHtT2uSFkfHXp299eNXzEh_XczFDo',
    appId: '1:1052417626402:web:5f6c51c067d0ae0475d57b',
    messagingSenderId: '1052417626402',
    projectId: 'notes-75136',
    authDomain: 'notes-75136.firebaseapp.com',
    storageBucket: 'notes-75136.firebasestorage.app',
    measurementId: 'G-1SSGHTQ13L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAatLE9leW5OSzx0TCbTI7DxItMmbaTm3Q',
    appId: '1:1052417626402:android:62c2524f94c6c6fa75d57b',
    messagingSenderId: '1052417626402',
    projectId: 'notes-75136',
    storageBucket: 'notes-75136.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCHMebiP-3nOsXAl0b4nvZlBGsxrKgxJU',
    appId: '1:1052417626402:ios:d09c6128f4402df675d57b',
    messagingSenderId: '1052417626402',
    projectId: 'notes-75136',
    storageBucket: 'notes-75136.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCHMebiP-3nOsXAl0b4nvZlBGsxrKgxJU',
    appId: '1:1052417626402:ios:d09c6128f4402df675d57b',
    messagingSenderId: '1052417626402',
    projectId: 'notes-75136',
    storageBucket: 'notes-75136.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD46HmHtT2uSFkfHXp299eNXzEh_XczFDo',
    appId: '1:1052417626402:web:6ab4da1a6ec8627d75d57b',
    messagingSenderId: '1052417626402',
    projectId: 'notes-75136',
    authDomain: 'notes-75136.firebaseapp.com',
    storageBucket: 'notes-75136.firebasestorage.app',
    measurementId: 'G-5K6C90D700',
  );

}